### ISSUE TITLE
Add countdown timer

### ISSUE THREAD

**Issue by nathan-van-der-werf** [adrenth/oc-coffeemanager-plugin#20]
Add a countdown timer which counts down until the designated participant will be picked. This can be added under the "expires at" (we can also replace the "expires at" with the countdown timer);

**Comment by nathan-van-der-werf** [comment]
Countdown should count down to whole minutes (xx:00 instead of (for example) xx:18)); since the cronjob runs every xx:00.

**Comment by adrenth** [comment]
I've set the `expired_at` to `Y-m-d H:i:0` (e.g. `2019-02-05 18:25:00`). Now it should count down properly.
